services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    # env_file:
    #   - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 
    depends_on:
      - sqlite3
      - redis
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - db_data:/root/db/
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
  bundle:
